name: flutter_brick
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/onecodemanzh/flutter-brick

# 下面这行代码防止包被意外发布到
# pub.dev使用pub publish。这是私有包的首选。
#如果你想发布到pub.dev，请删除publish_to: none
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  pro_image_editor: ^4.3.3
  universal_html: ^2.2.4
  get: ^5.0.0-release-candidate-6
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^10.0.1
  intl: ^0.19.0
  brick_bootstrap5_plus: 
    git:
      url: https://github.com/onecodemanzh/brick-bootstrap5-plus
  pluto_grid: ^8.0.0
  dio: ^5.5.0+1
  flutter_easyloading: ^3.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
