// ignore_for_file: constant_identifier_names
part of '../render.dart';

enum Fn {
  setValue,
  initStore,
  BuildId_change_refresh_Map,
  refresh_Map,
  array_exclude,
  clearUrlQuery,
  batchDownload,
  selectCurrentRow,
  patchValue_model,
  patchValue_model_submission,
  upload,
  setSelectOptionsByMap,
  setColumn,
  setSelectOptions,
  setSelectOptions_List,
  setSelectOptions_List_Form,
  search_then_getList,
  clearSelect,
  Return,
  init,
  getList,
  filter,
  add,
  getRow,
  getRow_form,
  resetForm,
  remove_selected_row,
  import,
  importExcel,
  getDocumentList,
  getFormFields,
  download,
  keepValue,
  updateSubConPermission,
  setList,
  cellClickedJump,
  setListFieldEmpty,
  setPagination,
  setBaseMap,
  set_UserInfo_and_Login,
  login,
  save,
  closeModal,
  filter_GroupType,
  add_level_list,
  add_list,
  getInitPreset,
  setFormEnabledAndDisabled,
  patchValue_model_photoList,
  generate,
  clearUserData_selectnode,
  validateForm,

  /// 提交表单
  submitForm,

  /// 初始化地图
  initMap,
  setBtnDisabled,
}
